version: '3.8'

services:
  database:
    image: "postgres"
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  app:
    image: "cat-toxic-plant-api"
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: app
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres